name = "verifier_normal_forms"
version = "0.1.0"
defaultTargets = ["VerifierNormalForms"]
testDriver = "Test"

[[lean_lib]]
name = "VerifierNormalForms"

[[lean_lib]]
name = "Test"
globs = ["Test.+"]

